name: Deploy

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t it21katsuravn/demo-api .

      - name: Login DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Push image
        run: docker push it21katsuravn/demo-api

      - name: SSH Deploy
        uses: appleboy/ssh-action@v1
        with:
          host: 192.168.101.58
          username: it21
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            docker pull it21katsuravn/demo-api
            docker stop demo-api || true
            docker rm demo-api || true
            docker run -d -p 3000:3000 --name demo-api it21katsuravn/demo-api